apiVersion: v1
kind: Service
metadata:
  namespace: staging
  name: sosmed-cilsy
  labels:
    app: sosmed-cilsy
    service: sosmed-cilsy
spec:
  type: LoadBalancer
  selector:
    app: sosmed-cilsy
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: staging
  name: sosmed-cilsy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sosmed-cilsy
      version: v1
  template:
    metadata:
      labels:
        app: sosmed-cilsy
        version: v1
    spec:
      containers:
        - name: sosmed-cilsy
          image: asefamarudin/asefsosmed:latest
          ports:
            - protocol: TCP
              containerPort: 80
          env:
            - name: DB_HOST
              value: sp-db.cjl3t5v4me3d.ap-southeast-1.rds.amazonaws.com
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: stg-secrets
                  key: DB_NAME
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: stg-secrets
                  key: DB_PASS
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: stg-secrets
                  key: DB_USER
          volumeMounts:
            - name: config-php
              mountPath: /var/www/html/config.php
              subPath: config.php
      volumes:
        - name: config-php
          configMap:
            name: config-php
